name: publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  publish:
    if: ${{ github.repository_owner == 'minori-ty' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: check version
        uses: EndBug/version-check@v2  # 当package.json version发生变化时，才会重新打包
        id: check

      - name: set version
        id: version
        run: |
          echo "MY_VERSION=${{ steps.check.outputs.version }}" >> $GITHUB_ENV
          echo "------------------------------"
          echo "version is ${{ steps.check.outputs.version }}"
          echo "------------------------------"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Gen npmrc
        run: echo "//registry.npmjs.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc

      - name: Build & publish
        if: steps.check.outputs.changed == 'true'
        run: sh ./script/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          TAG_VERSION: ${{ steps.check.outputs.version }}
          REGISTRY: https://registry.npmjs.com/
          FORCE_COLOR: 2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=4096
